### ISSUE TITLE
Lines that only have inline equations get centered (DOC file output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#12]
In blockquote and example block, the lines that only have inline equations get centered.

[ce-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3721998/ce-issue-sample.zip)

**Comment by opoudjis** [comment]
This is Word being clever: it is automatically assuming that any Math expression on its own in a paragraph has to be centered, because it's an equation.

The thing is, this is not that unreasonable an assumption. And this is an edgecase, because 

(a) the proper formatting of pseudocode, such as what you've got here, is to put a break line at the end of every new line, and not make each new line a new paragraph;

(b) properly, most of these expressions do not need to be MathML expressions anyway; `stem~1~` is entirely fine here

In any case, this default behaviour can be overridden easily in Asciidoctor, and I'm uncomfortable with making left alignment the default for such paragraphs:

````
[align=left]
stem:[ii"Rule"_1]
````

This works fine; and 

````
Rule~1~ +
````

is better. I do not believe a code fix is warranted.
