### ISSUE TITLE
Lines that include line-break character (+) get justified-aligned (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#13]
In blockquote, the lines that include line-break character (+) get justified-aligned (instead of left-aligned), making them look strange. (This only happens in doc output.)

[jl-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3722000/jl-issue-sample.zip)

**Comment by opoudjis** [comment]
This is because, exceptionally, blockquotes are in fact justified. 

In fact, that's because *all* paragraphs in ITU are supposed to be justified and I've only captured this for blockquotes as a new style. And this is the behaviour of line breaks in Word with justified paragraphs, and it's expected behaviour; the only reason we aren't seeing that in HTML is that HTML is not normally justified.

The workaround here is to prefix the paragraph involved with `[align=left]`. Unfortunately right  now alignment is only realised for paragraphs, not for blockquotes.

The *real* workaround is not to use blockquotes for what is not actually a blockquote function. That was a kludge on my part.

In fact, the real solution is for me to fast track something I was delaying: introduce "statements" (from https://github.com/metanorma/metanorma-standoc/issues/74), which are indented mathetmatical expressions, without being equations. Being mathematical, they should never be justified. Or alternatively, these should just be treated like all other pseudocode extracts, and the indentation treated as incidental.

**Comment by opoudjis** [comment]
Leaning to pseudocode, should be enough. Adding indent and font size to Word rendering of pseudocode.
