### ISSUE TITLE
`make` command does not build samples

### ISSUE THREAD

**Issue by bquast** [metanorma/mn-samples-itu#147]
Hello,

Thank you for this project. I really like it. Unfortunately, I missed the presentation you gave at ITU in 2019. But I definitely want to make use this (see how we can use it ourselves).\

When I run `make`, I get:

```
  [bquast@Latitude7420 mn-samples-itu]$ make
make: *** No targets specified and no makefile found.  Stop.
[bquast@Latitude7420 mn-samples-itu]$ 

```

the output of `bundle` was:

```
Installing metanorma-cli 1.6.1
Bundle complete! 1 Gemfile dependency, 224 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * `Zip::File`
  * `Zip::Entry`
  * `Zip::InputStream`
  * `Zip::OutputStream`

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
Post-install message from fontist:
Please run `fontist update` to fetch formulas.
Post-install message from rdf-xsd:

  For best results, use nokogiri and equivalent-xml gems as well.
  These are not hard requirements to preserve pure-ruby dependencies.
Post-install message from ruby-graphviz:

You need to install GraphViz (https://graphviz.org) to use this Gem.

For more information about Ruby-Graphviz :
* Doc: https://rdoc.info/github/glejeune/Ruby-Graphviz
* Sources: https://github.com/glejeune/Ruby-Graphviz
* Issues: https://github.com/glejeune/Ruby-Graphviz/issues
  [bquast@Latitude7420 mn-samples-itu]$ 
```

**Comment by bquast** [comment]
As a sidenote, it would be really interesting to use the built in workflow of GitHub or GitLab pages.

Jekyll (GitHub Pages) could work with jekyll-asciidoc (by asciidoctor), but it is not supported (I created an issue with GitHub Pages: https://github.com/github/pages-gem/issues/847). 

On GitLab Pages, Hugo has near-native support for asciidoctor (Ruby needs to be installed, and then the asciidoctor gem). The downside is that it doesn't have the same developer community and visibility as GitHub.

**Comment by ronaldtse** [comment]
@bquast thanks for raising this! The method of execution of this repository has changed since 2019 so it no longer uses Make. 

Metanorma also supports GitHub Pages and GitLab Pages. You could adopt from our workflows or other SDOs, e.g. OGC. We have a guide on how to use [Metanorma with CI/CD](https://www.metanorma.org/install/cicd/).

There are two general ways to run Metanorma:

* For the developer, you could install the `metanorma-cli` gem which you have done using the `bundle` command. After running `bundle`:
  * To generate all the samples in this repository, run `bundle exec metanorma site generate`. The output will generated under `site/`, which is a website that can be deployed via GitHub/GitLab Pages.
  * To only compile one document, run `bundle exec metanorma sources/G.191.adoc` (for example). The output will be located at the same location as the source file.

* For the normal user, we recommend either using the binary executable or the Docker container:
  * The executable can be installed via Homebrew (macOS), Snap (Linux) or Chocolatey (Windows). It will be runnable as `metanorma`. See the [install page](https://www.metanorma.org/install/) for details.
  * The [Docker container](https://github.com/metanorma/metanorma-docker) is offered on Docker Hub and it is referred to as `metanorma/metanorma:latest`. The instructions to use are [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjA3-y95o76AhWZat4KHV03B1kQFnoECAYQAQ&url=https%3A%2F%2Fwww.metanorma.org%2Finstall%2Fdocker%2F&usg=AOvVaw25e6i_W1MhCvsgqYWQhp9p).

**Comment by bquast** [comment]
Awesome, thank you. I will do that.

**Comment by ronaldtse** [comment]
@bquast On Arch Linux, the correct setup steps are now provided in #149 which are:

https://github.com/metanorma/mn-samples-itu/blob/b98f1208897fe1ad812b5b016fe30bf201a31528/.github/workflows/archlinux.yml#L19-L26

To build all the PDFs, run the `metanorma site generate --agree-to-terms` command:

https://github.com/metanorma/mn-samples-itu/blob/b98f1208897fe1ad812b5b016fe30bf201a31528/.github/workflows/archlinux.yml#L33-L35

Closing.
