### ISSUE TITLE
Convert ITU-T Editing Guidelines

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#20]
I've uploaded the ITU-T Editing Guidelines to reference-docs/. @anermina could you please help convert it? Thanks!

**Comment by ronaldtse** [comment]
Hope the formatting isn’t too difficult to achieve here. There are tables and sample referencing.

**Comment by anermina** [comment]
I'm not sure why authors labeled some tables as figures in the original document, but these are converted as tables using reverse_adoc. Since they are not figures/images even in the original document, I'm not sure how this should be interpreted in Metanorma... 

Is there a possibility to force changing the label from "Table" to "Figure"?

![image](https://user-images.githubusercontent.com/55683568/67598615-3dfd8980-f76e-11e9-965a-2f0c4b25fe4f.png)

**Comment by opoudjis** [comment]
Sorry, Nermina, I have not been monitoring these.

You can force a figure interpretation by embedding the table (unnumbered) within a figure, though I'll admit I'm not convinced that will work. Strictly speaking, this is an abuse of formatting. If that doesn't work, just leave it as a table for now. Moving to Metanorma is forcing some necessary loss of freedom...

**Comment by anermina** [comment]
@opoudjis Thanks, Nick.

Embedding the table within a figure results in this:
![image](https://user-images.githubusercontent.com/55683568/68088277-b5fa3c80-fe5d-11e9-86a4-859cdfa77742.png)

so I will just leave it as a table:
![image](https://user-images.githubusercontent.com/55683568/68088288-df1acd00-fe5d-11e9-8645-953c83d59780.png)

This is the original:
![image](https://user-images.githubusercontent.com/55683568/68088292-f063d980-fe5d-11e9-9aa5-fe263cd7dbbf.png)

**Comment by anermina** [comment]
This document is merged. Closing.
