### ISSUE TITLE
List titles get divided in lines (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#27]
If a list title is composed by two or more words, it gets divided in lines (one per word). Please, look at the sample below for clarification purposes.

[issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3773793/issue-sample.zip)

**Sample List:**

````
*Word1*:: Duis accumsan convallis lacus vehicula tristique. Integer maximus magna lorem, at 
ullamcorper ligula vestibulum id. Fusce fringilla velit libero, ut consequat ex pretium eget. Quisque
 vehicula convallis nulla, varius ullamcorper libero euismod eget. Donec consectetur id leo in 
tristique. Curabitur efficitur accumsan est, at volutpat risus elementum nec.

*Word1 Word2*:: Integer vitae mi mauris. Mauris dignissim venenatis lorem. Aliquam at arcu in felis 
mattis volutpat non nec felis. Vivamus placerat neque neque, ut tempus magna tristique eget. 
Suspendisse potenti. Curabitur id mollis mauris, ac pellentesque nunc.

*Word1 Word2 Word3*:: Suspendisse mattis mauris vel luctus suscipit. Nam porttitor ornare 
imperdiet. Pellentesque in nunc a sem porttitor tincidunt vitae vitae arcu. Maecenas sit amet ornare
 ligula. Quisque eu leo urna. Etiam pretium enim ullamcorper, consequat diam a, ornare libero. 
Vivamus neque metus, sagittis ac metus in, tincidunt ultricies dui. Ut ullamcorper sit amet libero et 
blandit.
````
![capture1](https://user-images.githubusercontent.com/33627611/67604628-14326b80-f74a-11e9-927c-0e39416aec12.JPG)

![capture2](https://user-images.githubusercontent.com/33627611/67604626-1399d500-f74a-11e9-8281-64a2ae494b27.JPG)

**Comment by opoudjis** [comment]
We have implemented definition lists as tables in Metanorma, and we are relying on Word autowidth here. (And believe me, the alternative is going to be unworkable, though I did consider it for https://github.com/metanorma/metanorma-itu/issues/43). It is Word autowidth that is deciding to wrap the left column. Keep Lines Together on the text in the left hand column is being ignored by Word.

I believe this is a Wontfix, though as with all Wontfixes, I would like @ronaldtse to confirm with ITU. Fixing a width on table columns means that, inevitably, one table or other will have to be manually adjusted; it is a worse default than autowidth. Making the spaces in the terms of the definition list be non-breaking spaces would force them to appear all on the same line; but that is a drastic enough solution, I do not wish to automate it.

Ugly as this is, I think this is preferable to the alternatives. Ronald does not like me saying this, but I believe that some post-editing of Word output, to get it to look just so, is inevitable; and this is not something that Word allows much control either.

Because we have defined this as a definition list in markup, there is no space in markup currently to define a width for the left hand column. We could do that; I really really would not want to.

We can always revert to ITU's styling of definition lists as just list paragraphs; but I am also reluctant to do that without go-ahead from @ronaldtse.

**Comment by ronaldtse** [comment]
> Because we have defined this as a definition list in markup, there is no space in markup currently to define a width for the left hand column. We could do that; I really really would not want to.

I think an option of "non-breaking term" (of the left column) is a reasonable alternative.

**Comment by opoudjis** [comment]
> I think an option of "non-breaking term" (of the left column) is a reasonable alternative.

The only way that is feasible is by replacing all spaces in the left term with non-breaking spaces in Word output. Is that what you want?

I think that would be a bad idea.

**Comment by opoudjis** [comment]
The alternative of fixed width will also not generalise. We are electing to document that this is an issue, and suggest people use non breaking space.
